config/routes.rb
Rails.application.routes.draw do
  get "/" => "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/register.rb
class Register < ApplicationRecord
  validates :title, presence: true, length: {maximum: 20}
  validates :start, presence: true
  validates :finish, presence: true
  validates :memo, length: {maximum: 500}
  
  validate :start_end_check

  def start_end_check
    if self.start.nil? || self.finish.nil?
      errors.add(:start, :finish)
    elsif  self.start >= self.finish 
      errors.add(:finish)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @registers = Register.all
  end
 
  def new
    @register = Register.new
  end
 
  def create
    @register = Register.new(params.require(:register).permit(:title, :start, :finish, :whole, :memo))
    if @register.save
      flash[:notice] = "登録しました"
      redirect_to :posts
    else
      flash[:notice] = "登録に失敗しました"
      render "new"
    end
  end
 
  def show
    @register = Register.find(params[:id])
  end
 
  def edit
    @register = Register.find_by(id: params[:id])
  end
 
  def update
    @register = Register.find_by(id: params[:id])
    if
      @register.update(params.require(:register).permit(:title, :start, :finish, :whole, :memo))
      flash[:notice] = "更新しました"
      redirect_to :posts
    else
      flash[:notice] = "更新に失敗しました"
      render "edit"
    end
  end
 
  def destroy
    @register = Register.find(params[:id])
    @register.destroy
    flash[:notice] = "削除しました"
    redirect_to :posts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/css/bootstrap-material-datetimepicker.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/js/bootstrap-material-datetimepicker.min.js"></script>
    <script>
      $(function(){
      $("#picker").bootstrapMaterialDatePicker({
      weekStart:0,
      format:"YYYY-MM-DD HH:mm"
      });
      });
    </script>
  </head>
    <header>
      <h1>スケジュール管理アプリ</h1>
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
    </header>
    

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/posts/edit.html.erb
<div class="edit_wrapper">
  <h3>編集してください</h3>
  
  <%= form_with model: @register, url: post_path, scope: :register do |register| %>
    <table class="table_edit">
      
      <tr>
        <th><%= register.label :title ,"タイトル" %></th>
        <td><%= register.text_field :title %></td>
      </tr>
      
      <tr>
        <th><%= register.label :start ,"開始日" %></th>
        <td><%= register.date_field :start %></td>
      </tr>
      
      <tr>
        <th><%= register.label :finish ,"終了日" %></th>
        <td><%= register.date_field :finish %></td>
      </tr>
      
      <tr>
        <th><%= register.label :whole ,"終日" %></th>
        <td><%= register.check_box :whole, {}, checked_value = "true", unchecked_value = "false" %></td>
      </tr>
      
      <tr>
        <th><%= register.label :memo ,"メモ" %></th>
        <td><%= register.text_area :memo %></td>
      </tr>
    </table>
    <%= register.submit "更新する" %>
  
  <% end %>
  
  <%= link_to("キャンセル", "/") %>
</div>

app/views/posts/index.html.erb
<div class="index">
  
  <h3>予定一覧</h3>
  
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>タイトル</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>終日</th>
        <th>更新日</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    
    <tbody>
      <% @registers.each do |register| %>
      <tr>
        <td><%= register.id %></td>
        <td><%= register.title %></td>
        <td><%= register.start.strftime("%Y/%m/%d") %></td>
        <td><%= register.finish.strftime("%Y/%m/%d") %></td>
        <td>
              <% if register.whole == true %>
                ◯
              <% else register.whole == false %>
              
              <% end %>
          </td>
        <td><%= register.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to("詳細", "/posts/#{register.id}") %></td>
        <td><%= link_to("編集", "/posts/#{register.id}/edit") %></td>
        <td><%= link_to("削除", "/posts/#{register.id}", method: :delete, data: {confirm: '本当に削除しますか?'}) %></td>
      </tr>
      
      <% end %>  
    </tbody>
  </table>
  
  <p><%= link_to("新規登録", "/posts/new", {class: "btn btn-light"}) %></p>

<%= "予定の合計：#{Register.count}" %><br>
<%= "本日の日付：#{Date.today.strftime("%Y/%m/%d")}" %>

</div>

app/views/posts/new.html.erb
<div class="new">
  
  <h3>予定の新規追加</h3>
  
  <%= form_with model: @register, url: posts_path, scope: :register do |register| %>
    <table class="table_new">
      <tr>
        <th><%= register.label :title ,"タイトル" %></th>
        <td><%= register.text_field :title %></td>
      </tr>
      
      <tr>
        <th><%= register.label :start ,"開始日" %></th>
        <td><%= register.date_field :start %></td>
      </tr>
      
      <tr>
        <th><%= register.label :finish ,"終了日" %></th>
        <td><%= register.date_field :finish %></td>
      </tr>
      
      <tr>
        <th><%= register.label :whole ,"終日" %></th>
        <td><%= register.check_box :whole, {}, true, false %></td>
      </tr>
      
      <tr>
        <th><%= register.label :memo ,"メモ" %></th>
        <td><%= register.text_area :memo %></td>
      </tr>
  
    </table>
  <%= register.submit "保存" %>
    
  <% end %>
  <%= link_to("キャンセル", "/") %>
    
</div>

app/views/posts/show.html.erb
<div class="show_wrapper">
  <div class="show_top">
    <h3>詳細ページ</h3>
    <%= link_to("一覧へ", "/") %>
    <%= link_to("編集へ", edit_post_path) %>
  </div>
  <table class="table_show">
    <tr>
      <th>タイトル</th>
      <td><%= @register.title %></td>
    </tr>
    
    <tr>
      <th>開始日</th>
      <td><%= @register.start %></td>
    </tr>
    
    <tr>
      <th>終了日</th>
      <td><%= @register.finish %></td>
    </tr>
    
    <tr>
      <th>終日</th>
      <td>
        <% if @register.whole == 0 %>
              ◯
        <% else @register.whole == false %>
            
        <% end %>
      </td>
    </tr>
    
    <tr>
      <th>メモ</th>
      <td><%= @register.memo %></td>
    </tr>
    
  </table>
</div>